### ISSUE TITLE
Still waiting

### ISSUE THREAD

**Issue by fregante** [mcollina/node-bob#1]
# 😮 

<img width="254" alt="screen shot 2017-09-08 at 02 08 22" src="https://user-images.githubusercontent.com/1402241/30180586-95184cee-943a-11e7-8743-a9f6048cb7bd.png">

# 😯 

<img width="113" alt="screen shot 2017-09-08 at 02 08 25" src="https://user-images.githubusercontent.com/1402241/30180606-a89e7478-943a-11e7-99bd-ff288187cc96.png">

**Comment by mcollina** [comment]
how did you find this? :D

**Comment by fregante** [comment]
Stalkando il tuo profilo in cerca di repo dal nome italiano 😃
